[tool.poetry]
name = "L3ES"
version = "0.0.0a0"
description = "Learned Lagrangian LES"
authors = ["Artur Toshev <artur.toshev@tum.de>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<=3.11"
jax = {version = "0.4.29", extras = ["cpu"]}
jaxlib = "0.4.29"
jax-sph = ">=0.1.0"
pillow = "^10.4.0"
jax-cfd = "^0.2.1"
xarray = "^2024.7.0"
seaborn = "^0.13.2"
finufft = "^2.5.0"

[tool.poetry.group.dev.dependencies]
pre-commit = ">=3.3.1"
ruff = "^0.9.5"
ipykernel = ">=6.25.1"

[tool.ruff]
exclude = [".git", ".venv", "venv"]
show-fixes = true
line-length = 88

[tool.ruff.lint]
ignore = ["F811", "E402"]
select = [
    "E", # pycodestyle
    "F", # Pyflakes
    "SIM", # flake8-simplify
    "I", # isort
]
