job_id_par: isoturb
reynolds: 2500.0
faku: 1.0  # velocity factor "fak*u"
initial_data: 1  # [0: white noise, 1: Kolmogorov, 2: CBC1, 3: CBC3, 4:Pao, 5: TGV, 6: Pao]  TODO: Pao in anfbed.f.sav
ntopleft: 4
ntopright: 0
captau: 1.0  # secondary filter differential form parameter
itsec: 0  # secodary filter incremental form parameter
isgs_model: 2  # [1: Smagorinsky, 2-4: no model]
alpha_prim: -0.2  # LES alpha for primary filter
alpha_sec: 0.2  # LES alpha for secondary filter
beta_prim: 0.0  # LES beta. Specify either alpha or beta
beta_sec: 0.0  # LES beta for secondary filter
itype_prim: 1  # Primary LES filter [1: Pade, 2: Gauss]
itype_sec: 1  # Secondary LES filter [1: Pade, 2: Power-Gauss]
iord_decon: -1  # LES only
iord_sec: -1  # Secondary filter order [>0: specified, 0: unspecified, <0: defined from primary]
iord_primreg: -1  # unused
dir_string: /home/atoshev/code/sphit/data_hit  # unused