mode: simulate  # [simulate, integrate]
gpu: 0
float64: True

sim:
  case: "HIT"
  N: 192
  dim: 3
  nu: 0.000625  # 1/1600=1/Re
  t_final: 5.0
  dt: 0.002
  u_ref: 4.0
  seed: 42
  log_freq: 100
  vis_freq: 100
  ckp_freq: 1
  ckp_N: 32
  dst_path: "results_hit_192/"

int:
  dst_path: "results_hit_192/"
  state_0_path: "data_relaxed/tgv_3_0.19634954_42.h5"
  splits: 8