mode: simulate  # [simulate, integrate]
gpu: 0
float64: True
xla_mem_fraction: 0.5
seed: 42

sim:
  case: "Kolm"
  N: 256
  dim: 2
  nu: 0.001  # from JAX-CFD
  t_final: 10.5  # +0.5 to remove the first 1k steps
  dt: 0.0005  # h/11U = 2pi/64/(11*7) = 0.001275 => 0.001; JAX-CFD(nu=0.001, 256^2, v_max=7) leads to dt=0.00175
  u_ref: 7.0
  log_freq: 100
  vis_freq: 100
  ckp_freq: 1000000
  ckp_N: 64
  dst_path: "results_kolm64_1/"

int:
  dst_path: "results_kolm64_1/"
  state_0_path: "data_relaxed/rlx_2_0.0981747704_0.h5"
  splits: 8
  relax: True
  vis_freq: 100

com:
  log_freq: 100
  vis_freq: 1000
  ckp_freq: 1
  dst_path: "results_kolm64_1/"