mode: simulate  # [simulate, integrate]
gpu: 0
float64: True

sim:
  case: "Kolm"
  N: 256
  dim: 2
  nu: 0.001  # 1/1600=1/Re
  t_final: 1.0
  dt: 0.001  # 0.00173 was computed
  u_ref: 7.0
  seed: 42
  log_freq: 100
  vis_freq: 100
  ckp_freq: 1
  ckp_N: 32
  dst_path: "results_kolm/"

int:
  dst_path: "results_kolm/"
  splits: 8