mode: simulate 
gpu: 0
float64: True
seed: 42
rejit: False

sim:
  case: "TGV3D"
  N: 64
  dim: 3
  nu: 0.000625  # 1/1600=1/Re
  t_final: 0.1
  t_burnin: 0.0
  burnin: 0
  dt: 0.01
  u_ref: 1.0
  ckp_N: 32
  log_freq: 5
  vis_freq: 5
  ckp_freq: 5
  dst_path: "results/tgv3d_validate/"
